export const MESSAGES = {
  ALL_POSTS: 'All posts',
  AGREEMENT_IS_NOT_CHECKED: 'You must promise that typed account is yours',
  COMMENT: 'Comment',
  COMMENTS: 'Comments',
  INVALID_CREDENTIALS: 'Invalid credentials',
  LIKES: 'Likes',
  LOADING: 'Loading... Please wait',
  NO_COMMENTS: 'No Comments',
  PASSWORD_IS_EMPTY: 'Password is empty',
  PASSWORD_IS_SHORT: 'Password should be at least 6 symbols',
  POSTED_AT: 'Posted at',
  USERNAME_IS_EMPTY: 'Username is empty',
  INVALID_POST_ID: 'Post not found',
  USER_EXISTS: 'User with this name already exists',
  USER_DOES_NOT_EXIST: 'User with this name does not exist',
  INVALID_ACCESS_TOKEN: 'Invalid access token',
} as const
